#!/usr/bin/env python3
"""Generate the dataset CATALOG + per-dataset SCHEMA pages from ``scripts/catalog.json``.

The served data surface is DATA — the producer's per-endpoint contracts, compiled
into ``scripts/catalog.json`` by ``build_catalog.py`` (from the live
``sovai-catalog/index.json`` when it exists, else from the producer repo's
immutable pandera/endpoint contracts). Hand-writing a catalogue page and a
column table per dataset is the exact "second list to forget to update" that goes
stale silently — the same failure ``self-cleaning-new``'s generated
``docs/PIPELINES.md`` + ``test_docs_consistency`` exists to prevent.

So these pages are GENERATED, never hand-edited:

* ``realtime-datasets/dataset-catalog.md`` — every served endpoint with its
  serving bucket, partitioning, column count and freshness.
* ``realtime-datasets/schema/<endpoint>.md`` — one column table per endpoint
  (name, type, nullable, unit, description) from the manifest ``column_dict``.
* ``SUMMARY.md`` — a marker-delimited "Data Catalog" section is kept in sync.

Everything outside the SUMMARY markers is never touched. Output is deterministic
(no timestamps), so ``--check`` is a byte-compare drift gate for CI.

Usage
-----
    python scripts/gen_catalog_docs.py            # write the pages + SUMMARY block
    python scripts/gen_catalog_docs.py --check    # exit 1 if anything is stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

_HERE = Path(__file__).resolve()
_REPO_ROOT = _HERE.parent.parent
_CATALOG_PATH = _REPO_ROOT / "scripts" / "catalog.json"
_CATALOG_PAGE = _REPO_ROOT / "realtime-datasets" / "dataset-catalog.md"
_SCHEMA_DIR = _REPO_ROOT / "realtime-datasets" / "schema"
_SUMMARY = _REPO_ROOT / "SUMMARY.md"

_GEN_MARK = "<!-- GENERATED by scripts/gen_catalog_docs.py — do not edit by hand. -->"
_SUMMARY_BEGIN = "<!-- BEGIN GENERATED: DATA CATALOG -->"
_SUMMARY_END = "<!-- END GENERATED: DATA CATALOG -->"
_SUMMARY_ANCHOR = "## Asset Managment"  # insert the block just before this section


def _slug(endpoint: str) -> str:
    return endpoint.replace("/", "-")


def _title(endpoint: str) -> str:
    """Human-ish title: 'spending/contracts' -> 'Spending / Contracts'."""
    return " / ".join(part.replace("_", " ").title() for part in endpoint.split("/"))


def _partitioning(ds: dict[str, Any]) -> str:
    prov = ds.get("provenance") or {}
    parts = []
    if prov.get("has_ticker_path"):
        parts.append("by ticker")
    if prov.get("has_date_path"):
        parts.append("by date")
    if prov.get("has_year"):
        parts.append("by year")
    return ", ".join(parts) if parts else "flat / unpartitioned"


def _freshness(ds: dict[str, Any]) -> str:
    fr = ds.get("freshness") or {}
    verdict = fr.get("verdict")
    if verdict and verdict != "unknown":
        watermark = fr.get("watermark") or "—"
        cadence = fr.get("cadence") or "—"
        return f"{verdict} (watermark {watermark}, cadence {cadence})"
    return "Not yet measured"


def _md_escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------
def render_catalog_page(catalog: dict[str, Any]) -> str:
    datasets = catalog.get("datasets", [])
    source = catalog.get("source", "unknown")
    versions = catalog.get("producer_versions", {})
    ver = versions.get("manifest_version") or versions.get("index_version") or "unknown"

    lines: list[str] = [
        "---",
        "description: >-",
        "  Every dataset served over the SovAI data API, generated from the frozen",
        "  serving-manifest contract — bucket, partitioning, column count and freshness.",
        "icon: table-list",
        "---",
        "",
        _GEN_MARK,
        "",
        "# Dataset Catalog",
        "",
        "{% hint style=\"info\" %}",
        "This page is **generated** from the served data catalog "
        "(`sovai-catalog/index.json` + the per-bucket `_meta/manifest.json`), compiled by "
        "`scripts/build_catalog.py`. Do not edit it by hand — edit the source and run "
        "`python scripts/gen_catalog_docs.py`.",
        "{% endhint %}",
        "",
        f"**Source:** `{source}` · **manifest/index version:** `{ver}` · "
        f"**{len(datasets)} served endpoints**.",
        "",
        "Each endpoint is read with `sov.data(\"<endpoint>\")`. `Freshness` shows "
        "*Not yet measured* until a producer export publishes the per-bucket manifest; "
        "it fills in automatically once the live catalog is populated.",
        "",
        "| Endpoint | Pipeline | Serving bucket | Partitioning | Columns | Freshness | Schema |",
        "|----------|----------|----------------|--------------|--------:|-----------|--------|",
    ]
    for ds in datasets:
        endpoint = ds["endpoint"]
        slug = _slug(endpoint)
        lines.append(
            f"| `{endpoint}` | `{ds.get('pipeline','')}` | `{ds.get('serving_bucket','')}` "
            f"| {_partitioning(ds)} | {ds.get('column_count', 0)} | {_freshness(ds)} "
            f"| [columns](schema/{slug}.md) |"
        )
    lines.append("")
    return "\n".join(lines) + "\n"


def render_schema_page(ds: dict[str, Any]) -> str:
    endpoint = ds["endpoint"]
    columns = ds.get("columns", [])
    lines: list[str] = [
        "---",
        "description: >-",
        f"  Served column schema for the `{endpoint}` dataset, generated from the",
        "  serving manifest's column dictionary.",
        "icon: table-columns",
        "---",
        "",
        _GEN_MARK,
        "",
        f"# {_title(endpoint)}",
        "",
        "{% hint style=\"info\" %}",
        "Generated column table for the served endpoint "
        f"`{endpoint}`. Edit the catalog source, not this page.",
        "{% endhint %}",
        "",
        "| | |",
        "|---|---|",
        f"| **SDK call** | `sov.data(\"{endpoint}\")` |",
        f"| **Pipeline** | `{ds.get('pipeline','')}` |",
        f"| **Serving bucket** | `{ds.get('serving_bucket','')}` |",
        f"| **Partitioning** | {_partitioning(ds)} |",
        f"| **Columns** | {ds.get('column_count', 0)} |",
        f"| **Freshness** | {_freshness(ds)} |",
        "",
        "## Columns",
        "",
    ]
    if columns:
        lines += [
            "| # | Column | Type | Nullable | Unit | Description |",
            "|--:|--------|------|:--------:|------|-------------|",
        ]
        for i, col in enumerate(columns, start=1):
            dtype = col.get("dtype")
            dtype_cell = f"`{dtype}`" if dtype else "—"
            nullable = "yes" if col.get("nullable") else "no"
            unit = _md_escape(col.get("unit") or "") or "—"
            desc = _md_escape(col.get("description") or "") or "—"
            lines.append(
                f"| {i} | `{_md_escape(col.get('name',''))}` | {dtype_cell} "
                f"| {nullable} | {unit} | {desc} |"
            )
    else:
        lines += [
            "{% hint style=\"warning\" %}",
            "No column dictionary is available for this endpoint yet. It is populated "
            "once the per-bucket manifest is published (or the producer contracts expose "
            "a matching pandera schema).",
            "{% endhint %}",
        ]
    lines.append("")
    return "\n".join(lines) + "\n"


def render_summary_block(catalog: dict[str, Any]) -> str:
    datasets = catalog.get("datasets", [])
    lines = [
        _SUMMARY_BEGIN,
        "",
        "## Data Catalog",
        "",
        "* [Dataset Catalog](realtime-datasets/dataset-catalog.md)",
    ]
    for ds in datasets:
        endpoint = ds["endpoint"]
        lines.append(
            f"  * [{_title(endpoint)}](realtime-datasets/schema/{_slug(endpoint)}.md)"
        )
    lines += ["", _SUMMARY_END]
    return "\n".join(lines)


def _splice_summary(current: str, block: str) -> str:
    """Insert or replace the marker-delimited block in SUMMARY.md."""
    if _SUMMARY_BEGIN in current and _SUMMARY_END in current:
        pre = current[: current.index(_SUMMARY_BEGIN)]
        post = current[current.index(_SUMMARY_END) + len(_SUMMARY_END) :]
        return pre + block + post
    # First insertion: place the block just before the anchor section.
    if _SUMMARY_ANCHOR in current:
        idx = current.index(_SUMMARY_ANCHOR)
        return current[:idx] + block + "\n\n" + current[idx:]
    # Fallback: append.
    return current.rstrip() + "\n\n" + block + "\n"


# ---------------------------------------------------------------------------
# Plan of files to write
# ---------------------------------------------------------------------------
def _planned_files(catalog: dict[str, Any]) -> dict[Path, str]:
    planned: dict[Path, str] = {_CATALOG_PAGE: render_catalog_page(catalog)}
    for ds in catalog.get("datasets", []):
        planned[_SCHEMA_DIR / f"{_slug(ds['endpoint'])}.md"] = render_schema_page(ds)
    current_summary = _SUMMARY.read_text() if _SUMMARY.exists() else ""
    planned[_SUMMARY] = _splice_summary(current_summary, render_summary_block(catalog))
    return planned


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if any generated file is stale")
    args = parser.parse_args()

    if not _CATALOG_PATH.exists():
        sys.stderr.write(
            "scripts/catalog.json is missing — run `python scripts/build_catalog.py` first.\n"
        )
        return 1
    catalog = json.loads(_CATALOG_PATH.read_text())
    planned = _planned_files(catalog)

    # Schema pages that exist on disk but are no longer in the catalog are stale
    # (an endpoint was removed). Track them so both write and --check catch them.
    live_schema_files = {p for p in planned if p.parent == _SCHEMA_DIR}
    orphans = sorted(
        p for p in _SCHEMA_DIR.glob("*.md") if p not in live_schema_files
    ) if _SCHEMA_DIR.is_dir() else []

    if args.check:
        stale: list[str] = []
        for path, body in planned.items():
            current = path.read_text() if path.exists() else None
            if current != body:
                stale.append(str(path.relative_to(_REPO_ROOT)))
        for orphan in orphans:
            stale.append(f"{orphan.relative_to(_REPO_ROOT)} (orphaned — endpoint gone)")
        if stale:
            sys.stderr.write(
                "Catalog docs are STALE — regenerate with `python scripts/gen_catalog_docs.py`:\n  "
                + "\n  ".join(stale)
                + "\n"
            )
            return 1
        print(f"Catalog docs are up to date ({len(catalog.get('datasets', []))} endpoints).")
        return 0

    _SCHEMA_DIR.mkdir(parents=True, exist_ok=True)
    for path, body in planned.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body)
    for orphan in orphans:
        orphan.unlink()
    print(
        f"wrote {_CATALOG_PAGE.relative_to(_REPO_ROOT)}, "
        f"{len(catalog.get('datasets', []))} schema pages, and the SUMMARY.md block"
        + (f" (removed {len(orphans)} orphans)" if orphans else "")
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
